import { validate, type Schema } from "schema-utils";
import type { Compiler } from "webpack";
import schema from "./options.schema.json" with { type: "json" };
import type { IPWAWebpackPluginOptions } from "./options.js";

const pluginName = "PWAWebpackPlugin";

const configuration = {
  name: pluginName,
  baseDataPath: "options",
};

export class PWAWebpackPlugin {
  options: IPWAWebpackPluginOptions;

  constructor(options: IPWAWebpackPluginOptions) {
    const resolvedOptions = options ?? {};

    validate(schema as Schema, resolvedOptions, configuration);

    this.options = resolvedOptions;
  }
  apply(compiler: Compiler) {
    const { name } = this.options;
    // webpack module instance can be accessed from the compiler object,
    // this ensures that correct version of the module is used
    // (do not require/import the webpack or any symbols from it directly).
    const { webpack } = compiler;
    // Compilation object gives us reference to some useful constants.
    const { Compilation } = webpack;
    // RawSource is one of the "sources" classes that should be used
    // to represent asset sources in compilation.
    const { RawSource } = webpack.sources;
    const { done } = compiler.hooks;

    done.tapPromise(pluginName, async (stats) => {
      const { fullHash } = stats.compilation;

      console.log(`Hello ${name}! - ${fullHash}`);
    });

    compiler.hooks.thisCompilation.tap(pluginName, (compilation) => {
      // Tapping to the assets processing pipeline on a specific stage.
      compilation.hooks.processAssets.tap(
        {
          name: pluginName,

          // Using one of the later asset processing stages to ensure
          // that all assets were already added to the compilation by other plugins.
          stage: Compilation.PROCESS_ASSETS_STAGE_SUMMARIZE,
        },
        (assets) => {
          // "assets" is an object that contains all assets
          // in the compilation, the keys of the object are pathnames of the assets
          // and the values are file sources.

          // Iterating over all the assets and
          // generating content for our Markdown file.
          const content =
            "# In this build:\n\n" +
            Object.keys(assets)
              .map((filename) => `- ${filename}`)
              .join("\n");

          // Adding new asset to the compilation, so it would be automatically
          // generated by the webpack in the output directory.
          compilation.emitAsset(
            this.options.outputFile,
            new RawSource(content),
          );
        },
      );
    });



	}
}
