/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BaseRouteImport } from './routes/_base'
import { Route as LanguageRouteRouteImport } from './routes/$language/route'
import { Route as BaseIndexRouteImport } from './routes/_base.index'
import { Route as LanguageIndexRouteImport } from './routes/$language/index'
import { Route as LanguageBlogPostsPageRouteImport } from './routes/$language/blog/posts/$page'
import { Route as LanguageBlogPostPost_idRouteImport } from './routes/$language/blog/post/$post_id'
import { Route as LanguageBlogAuthorsPageRouteImport } from './routes/$language/blog/authors/$page'
import { Route as LanguageBlogAuthorPageRouteImport } from './routes/$language/blog/author/$page'

const BaseRoute = BaseRouteImport.update({
  id: '/_base',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRouteRoute = LanguageRouteRouteImport.update({
  id: '/$language',
  path: '/$language',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseIndexRoute = BaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseRoute,
} as any)
const LanguageIndexRoute = LanguageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LanguageRouteRoute,
} as any)
const LanguageBlogPostsPageRoute = LanguageBlogPostsPageRouteImport.update({
  id: '/blog/posts/$page',
  path: '/blog/posts/$page',
  getParentRoute: () => LanguageRouteRoute,
} as any)
const LanguageBlogPostPost_idRoute = LanguageBlogPostPost_idRouteImport.update({
  id: '/blog/post/$post_id',
  path: '/blog/post/$post_id',
  getParentRoute: () => LanguageRouteRoute,
} as any)
const LanguageBlogAuthorsPageRoute = LanguageBlogAuthorsPageRouteImport.update({
  id: '/blog/authors/$page',
  path: '/blog/authors/$page',
  getParentRoute: () => LanguageRouteRoute,
} as any)
const LanguageBlogAuthorPageRoute = LanguageBlogAuthorPageRouteImport.update({
  id: '/blog/author/$page',
  path: '/blog/author/$page',
  getParentRoute: () => LanguageRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$language': typeof LanguageRouteRouteWithChildren
  '/': typeof BaseIndexRoute
  '/$language/': typeof LanguageIndexRoute
  '/$language/blog/author/$page': typeof LanguageBlogAuthorPageRoute
  '/$language/blog/authors/$page': typeof LanguageBlogAuthorsPageRoute
  '/$language/blog/post/$post_id': typeof LanguageBlogPostPost_idRoute
  '/$language/blog/posts/$page': typeof LanguageBlogPostsPageRoute
}
export interface FileRoutesByTo {
  '/$language': typeof LanguageIndexRoute
  '/': typeof BaseIndexRoute
  '/$language/blog/author/$page': typeof LanguageBlogAuthorPageRoute
  '/$language/blog/authors/$page': typeof LanguageBlogAuthorsPageRoute
  '/$language/blog/post/$post_id': typeof LanguageBlogPostPost_idRoute
  '/$language/blog/posts/$page': typeof LanguageBlogPostsPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$language': typeof LanguageRouteRouteWithChildren
  '/_base': typeof BaseRouteWithChildren
  '/$language/': typeof LanguageIndexRoute
  '/_base/': typeof BaseIndexRoute
  '/$language/blog/author/$page': typeof LanguageBlogAuthorPageRoute
  '/$language/blog/authors/$page': typeof LanguageBlogAuthorsPageRoute
  '/$language/blog/post/$post_id': typeof LanguageBlogPostPost_idRoute
  '/$language/blog/posts/$page': typeof LanguageBlogPostsPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$language'
    | '/'
    | '/$language/'
    | '/$language/blog/author/$page'
    | '/$language/blog/authors/$page'
    | '/$language/blog/post/$post_id'
    | '/$language/blog/posts/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$language'
    | '/'
    | '/$language/blog/author/$page'
    | '/$language/blog/authors/$page'
    | '/$language/blog/post/$post_id'
    | '/$language/blog/posts/$page'
  id:
    | '__root__'
    | '/$language'
    | '/_base'
    | '/$language/'
    | '/_base/'
    | '/$language/blog/author/$page'
    | '/$language/blog/authors/$page'
    | '/$language/blog/post/$post_id'
    | '/$language/blog/posts/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LanguageRouteRoute: typeof LanguageRouteRouteWithChildren
  BaseRoute: typeof BaseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_base': {
      id: '/_base'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$language': {
      id: '/$language'
      path: '/$language'
      fullPath: '/$language'
      preLoaderRoute: typeof LanguageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base/': {
      id: '/_base/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    '/$language/': {
      id: '/$language/'
      path: '/'
      fullPath: '/$language/'
      preLoaderRoute: typeof LanguageIndexRouteImport
      parentRoute: typeof LanguageRouteRoute
    }
    '/$language/blog/posts/$page': {
      id: '/$language/blog/posts/$page'
      path: '/blog/posts/$page'
      fullPath: '/$language/blog/posts/$page'
      preLoaderRoute: typeof LanguageBlogPostsPageRouteImport
      parentRoute: typeof LanguageRouteRoute
    }
    '/$language/blog/post/$post_id': {
      id: '/$language/blog/post/$post_id'
      path: '/blog/post/$post_id'
      fullPath: '/$language/blog/post/$post_id'
      preLoaderRoute: typeof LanguageBlogPostPost_idRouteImport
      parentRoute: typeof LanguageRouteRoute
    }
    '/$language/blog/authors/$page': {
      id: '/$language/blog/authors/$page'
      path: '/blog/authors/$page'
      fullPath: '/$language/blog/authors/$page'
      preLoaderRoute: typeof LanguageBlogAuthorsPageRouteImport
      parentRoute: typeof LanguageRouteRoute
    }
    '/$language/blog/author/$page': {
      id: '/$language/blog/author/$page'
      path: '/blog/author/$page'
      fullPath: '/$language/blog/author/$page'
      preLoaderRoute: typeof LanguageBlogAuthorPageRouteImport
      parentRoute: typeof LanguageRouteRoute
    }
  }
}

interface LanguageRouteRouteChildren {
  LanguageIndexRoute: typeof LanguageIndexRoute
  LanguageBlogAuthorPageRoute: typeof LanguageBlogAuthorPageRoute
  LanguageBlogAuthorsPageRoute: typeof LanguageBlogAuthorsPageRoute
  LanguageBlogPostPost_idRoute: typeof LanguageBlogPostPost_idRoute
  LanguageBlogPostsPageRoute: typeof LanguageBlogPostsPageRoute
}

const LanguageRouteRouteChildren: LanguageRouteRouteChildren = {
  LanguageIndexRoute: LanguageIndexRoute,
  LanguageBlogAuthorPageRoute: LanguageBlogAuthorPageRoute,
  LanguageBlogAuthorsPageRoute: LanguageBlogAuthorsPageRoute,
  LanguageBlogPostPost_idRoute: LanguageBlogPostPost_idRoute,
  LanguageBlogPostsPageRoute: LanguageBlogPostsPageRoute,
}

const LanguageRouteRouteWithChildren = LanguageRouteRoute._addFileChildren(
  LanguageRouteRouteChildren,
)

interface BaseRouteChildren {
  BaseIndexRoute: typeof BaseIndexRoute
}

const BaseRouteChildren: BaseRouteChildren = {
  BaseIndexRoute: BaseIndexRoute,
}

const BaseRouteWithChildren = BaseRoute._addFileChildren(BaseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LanguageRouteRoute: LanguageRouteRouteWithChildren,
  BaseRoute: BaseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
